server:
  port: 11901
bk:
  base:
    url: https://bkce7.tobizit.com
    app_code:  new-cmdb
    app_secret:  pnzCmIC7lXkhrwjIGl4HTJz96Pc6OMtRUFls
    open_url: http://bkapi.bkce7.tobizit.com/api
    cmdb_url: http://cmdb.bkce7.tobizit.com/api

spring:
  mongodb:
    uri: mongodb://10.244.3.87:27017/bkce
  redis:
    host: 10.244.3.85
    port: 6379
    database: 9