server:
  port: 8080
bk:
  base:
    url: https://bkce7.tobizit.com
    app_code:  new-cmdb
    app_secret:  pnzCmIC7lXkhrwjIGl4HTJz96Pc6OMtRUFls
    open_url: http://bkapi.bkce7.tobizit.com/api
    cmdb_url: http://cmdb.bkce7.tobizit.com/api
    cmdb_inner_url: http://cmdb.bkce7.tobizit.com
spring:
  redis:
    host: cd-crs-pj131lww.sql.tencentcdb.com
    port: 28887
    database: 9
    password: 5_m93cTzeL:C7FH